#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(OUTNETPACKETMAKERTASK_LIB)
#  define OUTNETPACKETMAKERTASK_EXPORT Q_DECL_EXPORT
# else
#  define OUTNETPACKETMAKERTASK_EXPORT Q_DECL_IMPORT
# endif
#else
# define OUTNETPACKETMAKERTASK_EXPORT
#endif
